package com.josebieco.talentsvocations.core;

public enum PurchaseResult {
    OK, UNKNOWN_NODE, NO_CLASS_SELECTED, WRONG_CLASS, MAXED, NOT_ENOUGH_POINTS, PREREQUISITE_NOT_MET,
    SECONDARY_LOCKED, CAPSTONE_PRIMARY_ONLY, PRIMARY_CAPSTONE_REQUIRED, MULTICLASS_DISABLED
}
